FestiFact3/Controllers/OrganiserController.cs
using FestiFact3.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Model.Abstract;
using Model.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FestiFact3.Controllers
{
    public class OrganiserController : Controller
    {

        private IFestivalRepository repo;

        public OrganiserController(IFestivalRepository repository)
        {
            repo = repository;
        }

        // GET: Organiser
        [Authorize(Roles = "organiser")]
        public ActionResult Index()
        {
            var userManager = new ApplicationUserManager(new UserStore<ApplicationUser>(new ApplicationDbContext()));

            var user = userManager.FindById(User.Identity.GetUserId());

            IEnumerable<Festival> festivals = repo.FestivalByOrganiser(user.Id);

            return View(festivals);
        }

        [Authorize(Roles = "organiser")]
        public ActionResult DetailFestival(int id)
        {
            Festival festival = repo.FestivalById(id);
            IEnumerable<Performance> performances = repo.PerformancesByFestival(festival);
            IEnumerable<Stage> stages = repo.StagesByFestival(festival);

            ViewBag.stages = stages;
            ViewBag.performances = performances;
            ViewBag.soldTickets = repo.TicketsSold(id);
            ViewBag.ticketsLeft = repo.TicketsLeft(id);
            ViewBag.totalPerformances = repo.TotalPerformances(id);
            ViewBag.totalStages = repo.TotalStages(id);
            return View(festival);
        }

        [Authorize(Roles = "organiser")]
        public ActionResult CreateFestival()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "organiser")]
        public ActionResult CreateFestival(Festival festival)
        {
            if (ModelState.IsValid)
            {
                var userManager = new ApplicationUserManager(new UserStore<ApplicationUser>(new ApplicationDbContext()));
                var user = userManager.FindById(User.Identity.GetUserId());

                festival.OrganizerID = user.Id;

                repo.AddFestival(festival);

                return RedirectToAction("Index");
            }
            else
            {
                // There is a validation error
                return View();
            }
        }

        [Authorize(Roles = "organiser")]
        public ActionResult EditFestival(int id)
        {
            return View(repo.FestivalById(id));
        }

        [HttpPost]
        [Authorize(Roles = "organiser")]
        public ActionResult EditFestival(Festival festival)
        {
            if (ModelState.IsValid)
            {
                var userManager = new ApplicationUserManager(new UserStore<ApplicationUser>(new ApplicationDbContext()));
                var user = userManager.FindById(User.Identity.GetUserId());

                if (user.Id != festival.OrganizerID)
                {
                    return View("NotAuthorized");
                }

                repo.EditFestival(festival);
                return RedirectToAction("Index");
            }
            else
            {
                // There is a validation error
                return View();
            }
        }

        [Authorize(Roles = "organiser")]
        public ActionResult DeleteFestival(int id)
        {
            var userManager = new ApplicationUserManager(new UserStore<ApplicationUser>(new ApplicationDbContext()));
            var user = userManager.FindById(User.Identity.GetUserId());
            Festival festival = repo.FestivalById(id);

            if (user.Id != festival.OrganizerID)
            {
                return View("NotAuthorized");
            }

            repo.DeleteFestival(festival);

            return RedirectToAction("Index");
        }

        [Authorize(Roles = "organiser")]
        public ActionResult CreateStage(int id)
        {
            ViewBag.festival = repo.FestivalById(id);
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "organiser")]
        public ActionResult CreateStage(Stage stage, int festivalId)
        {
            if (ModelState.IsValid)
            {
                var userManager = new ApplicationUserManager(new UserStore<ApplicationUser>(new ApplicationDbContext()));
                var user = userManager.FindById(User.Identity.GetUserId());
                Festival festival = repo.FestivalById(festivalId);

                if (user.Id != festival.OrganizerID)
                {
                    return View("NotAuthorized");
                }

                stage.Festival = festival;

                repo.AddStage(stage);

                return RedirectToAction("DetailFestival", new { stage.Festival.Id });
            }
            else
            {
                // There is a validation error
                return View();
            }
        }

        [Authorize(Roles = "organiser")]
        public ActionResult EditStage(int id)
        {
            Stage stage = repo.StageById(id);
            ViewBag.festival = stage.Festival;
            return View(repo.StageById(id));
        }

        [HttpPost]
        [Authorize(Roles = "organiser")]
        public ActionResult EditStage(Stage stage, int festivalId)
        {
            if (ModelState.IsValid)
            {
                var userManager = new ApplicationUserManager(new UserStore<ApplicationUser>(new ApplicationDbContext()));
                var user = userManager.FindById(User.Identity.GetUserId());
                Festival festival = repo.FestivalById(festivalId);

                if (user.Id != festival.OrganizerID)
                {
                    return View("NotAuthorized");
                }

                stage.Festival = festival;

                repo.EditStage(stage);
                return RedirectToAction("DetailFestival", new { stage.Festival.Id });
            }
            else
            {
                // There is a validation error
                return View();
            }
        }

        [Authorize(Roles = "organiser")]
        public ActionResult DeleteStage(int id)
        {
            var userManager = new ApplicationUserManager(new UserStore<ApplicationUser>(new ApplicationDbContext()));
            var user = userManager.FindById(User.Identity.GetUserId());
            Stage stage = repo.StageById(id);

            if (user.Id != stage.Festival.OrganizerID)
            {
                return View("NotAuthorized");
            }

            int FestivalReturnId = stage.Festival.Id;
            repo.DeleteStage(stage);

            return RedirectToAction("DetailFestival", new { id = FestivalReturnId });
        }

        [Authorize(Roles = "organiser")]
        public ActionResult CreatePerformance(int id)
        {
            List<Stage> stages = repo.StagesByFestival(repo.FestivalById(id));
            List<SelectListItem> stagelist = new List<SelectListItem>();
            foreach(Stage stage in stages)
            {
                var stageListItem = new SelectListItem
                {
                    Text = stage.Name,
                    Value = stage.Id.ToString()
                };
                stagelist.Add(stageListItem);
            }
            SelectList stageSelectList = new SelectList(stagelist, "Value", "Text", 1);
            ViewBag.stageSelectList = stageSelectList;
            ViewBag.festival = repo.FestivalById(id);
            ViewBag.overlap = "";
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "organiser")]
        public ActionResult CreatePerformance(Performance performance, int festivalId, string stageId)
        {
            if (ModelState.IsValid)
            {
                var userManager = new ApplicationUserManager(new UserStore<ApplicationUser>(new ApplicationDbContext()));
                var user = userManager.FindById(User.Identity.GetUserId());
                Festival festival = repo.FestivalById(festivalId);

                if (user.Id != festival.OrganizerID)
                {
                    return View("NotAuthorized");
                }

                Stage stage = repo.StageById(Int32.Parse(stageId));
                performance.Stage = stage;

                string overlapResult = repo.AddPerformance(performance);
                if(overlapResult != "Success")
                {
                    //Overlap
                    List<Stage> stages = repo.StagesByFestival(repo.FestivalById(festivalId));
                    List<SelectListItem> stagelist = new List<SelectListItem>();
                    foreach (Stage stageIndu in stages)
                    {
                        var stageListItem = new SelectListItem
                        {
                            Text = stageIndu.Name,
                            Value = stageIndu.Id.ToString()
                        };
                        stagelist.Add(stageListItem);
                    }
                    SelectList stageSelectList = new SelectList(stagelist, "Value", "Text", 1);
                    ViewBag.stageSelectList = stageSelectList;
                    ViewBag.festival = repo.FestivalById(festivalId);
                    ViewBag.overlap = overlapResult;
                    return View();
                }
                return RedirectToAction("DetailFestival", new { id = festivalId });
            }
            else
            {
                //There is a validation error
                List<Stage> stages = repo.StagesByFestival(repo.FestivalById(festivalId));
                List<SelectListItem> stagelist = new List<SelectListItem>();
                foreach (Stage stageIndu in stages)
                {
                    var stageListItem = new SelectListItem
                    {

FestiFact3/Controllers/TicketController.cs
using FestiFact3.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Model.Abstract;
using Model.Models;
using QRCoder;
using Rotativa;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FestiFact3.Controllers
{
    public class TicketController : Controller
    {
        private IFestivalRepository repo;
        private ApplicationUserManager userManager;


        public TicketController(IFestivalRepository repository)
        {
            repo = repository;
        }

        // GET: Ticket
        public ActionResult Index()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }
            this.userManager = new ApplicationUserManager(new UserStore<ApplicationUser>(new ApplicationDbContext()));

            var user = userManager.FindById(User.Identity.GetUserId());

            IEnumerable<Ticket> tickets = repo.UserTickets(user.Id);

            return View(tickets);
        }

        public ActionResult BuyTicket(int id)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }
            this.userManager = new ApplicationUserManager(new UserStore<ApplicationUser>(new ApplicationDbContext()));

            var user = userManager.FindById(User.Identity.GetUserId());

            bool result = repo.AddTicket(user.Id, user.Email, id);

            if (result == false)
            {
                return RedirectToAction("Detail", "Festival", new { id });
            }
            else { return RedirectToAction("Index"); }    
        }

        public ActionResult Details(int id)
        {
            this.userManager = new ApplicationUserManager(new UserStore<ApplicationUser>(new ApplicationDbContext()));
            var user = userManager.FindById(User.Identity.GetUserId());

            Ticket ticket = repo.UserTicketById(id);

            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }
            else if (user.Id != ticket.UserId)
            {
                return RedirectToAction("List");
            }

            string code = ticket.UserEmail + "|" + ticket.Festival.Name + "|" + ticket.TicketId + "|" + ticket.BuyDateTime;
            QRCodeGenerator qrGenerator = new QRCodeGenerator();
            QRCodeData qrCodeData = qrGenerator.CreateQrCode(code, QRCodeGenerator.ECCLevel.Q);
            QRCode qrCode = new QRCode(qrCodeData);
            Bitmap qrCodeImage = qrCode.GetGraphic(20);

            var bitMapBytes = BitmapToBytes(qrCodeImage);
            ViewBag.qr = bitMapBytes;

            return new ViewAsPdf(ticket)
            {
                FileName = "Ticket.pdf"
            };
        }

        // This method is for converting bitmap into a byte array
        private static byte[] BitmapToBytes(Bitmap img)
        {
            using (MemoryStream stream = new MemoryStream())
            {
                img.Save(stream, System.Drawing.Imaging.ImageFormat.Png);
                return stream.ToArray();
            }
        }
    }
}

FestiFact3/Views/Shared/NotAuthorized.cshtml
@{
    ViewBag.Title = "NotAuthorized";
}

<h2>NotAuthorized</h2>

You are not authorized to view this page

FestiFact3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    <script src="@Url.Content("~/Scripts/jquery-ui-1.12.1.min.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery.datetimepicker.js")"></script>
    @Scripts.Render("~/bundles/bootstrap")
    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/modules/exporting.js"></script>
    <link href="@Url.Content("~/Content/themes/base/jquery-ui.min.css")" rel="stylesheet" />
    <link href="@Url.Content("~/Content/jquery.datetimepicker.css")" rel="stylesheet" />

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("FestiFact", "Index", "Festival", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Festival")</li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("My Tickets", "Index", "Ticket")</li>
                    }
                    @if (User.IsInRole("Admin"))
                    {
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                Manager <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Organisers", "ListOrganisers", "Admin")</li>
                                <li>@Html.ActionLink("Organiser Requests", "PendingOrganisers", "Admin")</li>
                            </ul>
                        </li>
                    }
                    @if (User.IsInRole("organiser"))
                    {
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                Organiser <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("My Festivals", "Index", "Organiser")</li>
                                <li>@Html.ActionLink("New Festival", "CreateFestival", "Organiser")</li>
                            </ul>
                        </li>
                    }                                      
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - FestiFact</p>
        </footer>
    </div>

    @RenderSection("scripts", required: false)
    <script>
        jQuery('.date-picker').datetimepicker({
            minDate: '-1970/01/01',
        });
    </script>
</body>
</html>